version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: sh -c "npm ci && npm start"
    ports:
      - "127.0.0.1:4200:4200"
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./api:/api
  web:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/api
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'josh'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'angularapp'
    command:
      - '--skip-log-bin'
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
volumes:
  node_modules: